#!/bin/bash
python3 $PYFILE

# Se hace un script de bash (este, que es el que subimos a github) donde se llame a la variable de entorno
# que creamos llamada: PYFILE --> esto se hace con: export PYFILE=main.py
# Para probar el codigo creamos un archivo con el interprete de python3 llamado: main.py donde le ponemos un
# print para que imprima: Best School
